services:
  banco_postgres_processo_seletivo:
    image: postgres:latest
    environment:
      POSTGRES_USER: contatita_user
      POSTGRES_PASSWORD: senhamuitoforte123
      POSTGRES_DB: contatita_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: